

image:
  - Python
  - Ubuntu

#branches:
#  only:
#    - master

install:
  - "python -m pip install --upgrade pip"
  - pip install pipenv
  - pipenv install --dev --system

build_script:
  - pipenv run build-exe
  - cmd: dir dist/*
  - sh: dir dist/*

artifacts:
  - path: dist/*

#deploy:
#  release: v$(appveyor_build_version)
#  description: 'Release description'
#  provider: GitHub
#  auth_token:
#    secure: <your encrypted token> # your encrypted token from GitHub
#  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only
