
image:
  - Visual Studio 2017
#  - Ubuntu

environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

#branches:
#  only:
#    - master

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install pipenv
  - pip install pypiwin32
  - pipenv install --dev --system

build_script:
  - pipenv run build-exe
  - cmd: dir dist
  - sh: ls dist/

artifacts:
  - path: dist/*

#deploy:
#  release: v$(appveyor_build_version)
#  description: 'Release description'
#  provider: GitHub
#  auth_token:
#    secure: <your encrypted token> # your encrypted token from GitHub
#  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only
